name: unbiased
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - ffmpeg=4.2.2
  - numpy=1.24.3
  - pillow=10.2.0
  - pip=24.2
  - python=3.8.18
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.1
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - plyfile==1.0.3
    - opencv-python==4.10.0.84
    # - submodules/diff-surfel-rasterization
    # - submodules/simple-knn